### ISSUE TITLE
Minsdkversion upgraded in minor version

### ISSUE THREAD

**Issue by latunsk4** [google/mobly-snippet-lib#115]
From 1.3.0 to 1.3.1 the minsdkversion was upgraded to 26. This is a breaking change. Is it possible to at least get 1.3.0 onto mavenCentral()? Thanks!

**Comment by xpconanfan** [comment]
Sorry about that.
You are right this should have been a major change, and not a minor ver bump.

Since `minsdkversion ` is just a gradle param, would you be able to build with your own gradle fork to work around this issue for now?

Also could you share more context on your use case so we can better help?
Thanks.

**Comment by xianyuanjia** [comment]
Added 1.3.0 to [mavenCentral](https://repo.maven.apache.org/maven2/com/google/android/mobly/mobly-snippet-lib/1.3.0/)

**Comment by latunsk4** [comment]
Thanks for the help!
